[pyprland]
plugins = [
  "scratchpads", "layout_center", "fetch_client_menu"
]

[scratchpads.term]
command = "alacritty --class alacritty-dropterm"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.gpt]
command = "firefox --name=chatgpt --no-remote -P chatgpt https://chat.openai.com/"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true


[scratchpads.password]
command = "keepassxc"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.notes]
command = "obsidian --disable-gpu"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[layout_center]
margin = 120
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"

[fetch_client_menu]
separator = " | "
